### ISSUE TITLE
Feature: User can create a event

### ISSUE THREAD

**Issue by AngelaJiaNan** [AngelaJiaNan/Run-with-me#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a event.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user can input the following details on the event pages: event title, date, place, starting time. When user enter the place of the event, below a google map will show the location. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-12-27 at 11 51 11 AM](https://user-images.githubusercontent.com/90875226/147503007-f26f00d2-604a-4ed4-b664-4bcf71e05411.png)

![Screen Shot 2021-12-27 at 11 51 36 AM](https://user-images.githubusercontent.com/90875226/147503025-5f322007-fb3c-42b7-a69d-0af61f58035d.png)
![Screen Shot 2021-12-27 at 11 52 45 AM](https://user-images.githubusercontent.com/90875226/147503079-5ae57707-0039-4b53-b08c-faaf5af8dc9d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database
- [x] create database for events
- [x] add rows: title, date, address, lat, lng, startingtime

### ☁️ Server

- [x] create endpoint POST to save a new event
- [x] Test with HTTPie
- [x] create endpoint GET to display created events
- [x] install calendar npm package 
- [x] install google map 

### ⚡ Client
- [x] Create a form page

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
