### ISSUE TITLE
Feature: User can edit event

### ISSUE THREAD

**Issue by AngelaJiaNan** [AngelaJiaNan/Run-with-me#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit the event 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-12-27 at 11 54 21 AM](https://user-images.githubusercontent.com/90875226/147503159-5218bf9a-2183-49ae-ad80-9fcb3893955a.png)
![Screen Shot 2021-12-27 at 11 56 08 AM](https://user-images.githubusercontent.com/90875226/147503261-d71273db-3936-44d6-a729-5f577aca16ea.png)
![Screen Shot 2021-12-27 at 11 57 06 AM](https://user-images.githubusercontent.com/90875226/147503332-e3cf68f3-3525-493e-84e2-076813d57ec3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server

- [x] create end point for PATCH /api/events for updating an existing event
- [x] Test with HTTPie

### ⚡ Client

- [x] Update component to with a edit BTN
- [x] when client change a part of the form, google map should update aswell

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
