### ISSUE TITLE
Feature: User can delete a event

### ISSUE THREAD

**Issue by AngelaJiaNan** [AngelaJiaNan/Run-with-me#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-12-27 at 11 58 38 AM](https://user-images.githubusercontent.com/90875226/147503415-66dc5606-1c99-45f1-84e6-3e9e6a0382ce.png)

![Screen Shot 2021-12-27 at 11 59 39 AM](https://user-images.githubusercontent.com/90875226/147503462-fb18be48-90a3-4887-a7e7-b1fa81596bb4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server

- [x] build Delete endpoint
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to for delete modal
- [x] create delete BTN
- [x]  add onCLick to delete BTN to open modal
- [x] add event listener on cancel BTN to close the modal
- [x] add event listener on confirem BTN to delete the event

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
